source "https://rubygems.org"

gem "rails", "~> 8.1.3"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "bootsnap", require: false
gem "rack-cors"
gem "bcrypt", "~> 3.1.7"

# Auth
gem "devise"
gem "devise-jwt"

# Background jobs
gem "sidekiq"

# CSV
gem "csv"
gem "smarter_csv"

# AI
gem "anthropic"

# Serialization
gem "blueprinter"

# Reduces boot times through caching; required in config/boot.rb
gem "redis"

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "rspec-rails"
  gem "factory_bot_rails"
  gem "faker"
  gem "shoulda-matchers"
end
